export const GET_PARKS_FAILURE='GET_PARKS_FAILURE'
export const GET_PARKS_SUCCESS='GET_PARKS_SUCCESS'
export const GET_FORM_VISIBLE='GET_FORM_VISIBLE'
export const GET_ADD_PARK_SUCCESS='GET_ADD_PARK_SUCCESS'